### PR TITLE
Decode entities in text nodes

### PR DESCRIPTION
**Pull request by dmsnell**
Note that this should involve a build stage so that the parser itself
doesn't look so ugly. I have included the body of `he` into the global
function area of the parser to give us `decode()`. `he` is a robust
library for encoding and decoding HTML entities.

The purpose of this change is to demonstrate how this is possible to
keep the character and entity encoding fully abstracted inasmuch as it
concerns the block renderers, editors, and core.

cc: @aduth @nylen @mtias @mcsf

### CODE REVIEW

**Comment by aduth** [comment]
We must attach `he`'s license if we're going to include it.

https://github.com/mathiasbynens/he/blob/master/LICENSE-MIT.txt

**Comment by dmsnell** [comment]
Thanks @aduth - I had originally taken it out when mashing together the IIFE from `he` - did not mean to strip away the reds

**Comment by dmsnell** [comment]
we should probably do this outside of the grammar itself but I wanted to keep more changes out of the PR

note that it's easier to have finer control over the encoding here in the grammar because we can make distinctions easily such as _decode attribute entities_ vs _decode general entities_

**Comment by dmsnell** [comment]
closing because this shouldn't be done during the PEG stage unless we use the JS-syntax for the grammar, which I don't want to do. this should be moved into a second stage.

**Pull request closed without merging**
